---
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
env:
  node: true
rules:
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: "explicit"
      overrides:
        accessors: "no-public"
        constructors: "no-public"
  "@typescript-eslint/member-ordering": "error"
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "prettier/prettier": "error"
overrides:
  - files: "*.js"
    rules:
      "@typescript-eslint/explicit-member-accessibility": "off"
