version: "3.7"

services:
  app:
    volumes: 
      - ./dist:/usr/src/app/dist
    ports:
      - "9229:9229"
    environment: 
      - NODE_ENV=development
    command: ["npm", "run", "watch-nodemon", "dist/bot.js"]
  db:
    env_file: 
      - .env.development
