discord:
  id:
  secret:
  guildLogs:
db:
  name:
  host: db
  port: 5432
  user: postgres
  secret:
redis:
  host: redis
  port: 6379
youtube:
  secret:
server: "https://www.pinkbean.xyz"
prefix:
  content: "$"
  space: false
devs:
